import type { AdminResourceName } from "../../../../types/api";
import type { ResourceConfig } from "./types";


export const resourceConfigs: Record<AdminResourceName, ResourceConfig> = {
    services: {
        title: "الخدمات",
        singular: "خدمة",
        description: "إدارة الخدمات وربطها بالمناطق وبيانات SEO.",
        defaults: {
            name: "",
            slug: "",
            shortDescription: "",
            description: "",
            imageUrl: "",
            icon: "",
            isActive: true,
            displayOrder: 0,
            metaTitle: "",
            metaDescription: "",
            areaIds: [],
        },
        fields: [
            {
                name: "name",
                label: "اسم الخدمة",
                type: "text",
                required: true,
                maxLength: 150,
            },
            {
                name: "slug",
                label: "الرابط المختصر",
                type: "text",
                required: true,
                maxLength: 180,
            },
            {
                name: "shortDescription",
                label: "الوصف المختصر",
                type: "textarea",
                span: true,
                required: true,
                maxLength: 500,
            },
            {
                name: "description",
                label: "الوصف الكامل",
                type: "textarea",
                span: true,
                required: true,
                maxLength: 4000,
            },
            {
                name: "imageUrl",
                label: "صورة الخدمة",
                type: "upload-image",
                span: true,
            },
            {
                name: "icon",
                label: "رمز الأيقونة",
                type: "text",
                maxLength: 100,
            },
            {
                name: "displayOrder",
                label: "ترتيب العرض",
                type: "number",
            },
            {
                name: "areaIds",
                label: "المناطق المرتبطة",
                type: "multi-areas",
                span: true,
            },
            {
                name: "metaTitle",
                label: "عنوان SEO",
                type: "text",
                span: true,
                required: true,
                maxLength: 200,
            },
            {
                name: "metaDescription",
                label: "وصف SEO",
                type: "textarea",
                span: true,
                required: true,
                maxLength: 500,
            },
            {
                name: "isActive",
                label: "الخدمة نشطة",
                type: "checkbox",
                span: true,
            },
        ],
    },

    areas: {
        title: "المناطق",
        singular: "منطقة",
        description: "إدارة مناطق التغطية والخدمات المرتبطة بها.",
        defaults: {
            name: "",
            slug: "",
            description: "",
            isActive: true,
            displayOrder: 0,
            metaTitle: "",
            metaDescription: "",
            serviceIds: [],
        },
        fields: [
            {
                name: "name",
                label: "اسم المنطقة",
                type: "text",
                required: true,
                maxLength: 150,
            },
            {
                name: "slug",
                label: "الرابط المختصر",
                type: "text",
                required: true,
                maxLength: 180,
            },
            {
                name: "description",
                label: "الوصف",
                type: "textarea",
                span: true,
                required: true,
                maxLength: 1500,
            },
            {
                name: "displayOrder",
                label: "ترتيب العرض",
                type: "number",
            },
            {
                name: "serviceIds",
                label: "الخدمات المرتبطة",
                type: "multi-services",
                span: true,
            },
            {
                name: "metaTitle",
                label: "عنوان SEO",
                type: "text",
                span: true,
                required: true,
                maxLength: 200,
            },
            {
                name: "metaDescription",
                label: "وصف SEO",
                type: "textarea",
                span: true,
                required: true,
                maxLength: 500,
            },
            {
                name: "isActive",
                label: "المنطقة نشطة",
                type: "checkbox",
                span: true,
            },
        ],
    },

    gallery: {
        title: "معرض الأعمال",
        singular: "صورة",
        description: "إدارة صور الأعمال وربطها بالخدمة والمنطقة.",
        defaults: {
            title: "",
            description: "",
            imageUrl: "",
            serviceId: 0,
            areaId: null,
            isFeatured: false,
            isActive: true,
            displayOrder: 0,
        },
        fields: [
            {
                name: "title",
                label: "عنوان الصورة",
                type: "text",
                required: true,
                maxLength: 200,
            },
            {
                name: "serviceId",
                label: "الخدمة",
                type: "select-service",
                required: true,
            },
            {
                name: "areaId",
                label: "المنطقة (اختياري)",
                type: "select-area",
            },
            {
                name: "description",
                label: "الوصف",
                type: "textarea",
                span: true,
                required: true,
                maxLength: 1000,
            },
            {
                name: "imageUrl",
                label: "الصورة",
                type: "upload-image",
                span: true,
                required: true,
            },
            {
                name: "displayOrder",
                label: "ترتيب العرض",
                type: "number",
            },
            {
                name: "isFeatured",
                label: "صورة مميزة",
                type: "checkbox",
            },
            {
                name: "isActive",
                label: "الصورة نشطة",
                type: "checkbox",
            },
        ],
    },

    videos: {
        title: "الفيديوهات",
        singular: "فيديو",
        description: "إدارة الفيديوهات والصور المصغرة وربطها بالخدمة.",
        defaults: {
            title: "",
            description: "",
            videoUrl: "",
            thumbnailUrl: "",
            serviceId: 0,
            areaId: null,
            isFeatured: false,
            isActive: true,
            displayOrder: 0,
        },
        fields: [
            {
                name: "title",
                label: "عنوان الفيديو",
                type: "text",
                required: true,
                maxLength: 200,
            },
            {
                name: "serviceId",
                label: "الخدمة",
                type: "select-service",
                required: true,
            },
            {
                name: "areaId",
                label: "المنطقة (اختياري)",
                type: "select-area",
            },
            {
                name: "description",
                label: "الوصف",
                type: "textarea",
                span: true,
                required: true,
                maxLength: 1000,
            },
            {
                name: "videoUrl",
                label: "ملف أو رابط الفيديو",
                type: "upload-video",
                span: true,
                required: true,
            },
            {
                name: "thumbnailUrl",
                label: "الصورة المصغرة",
                type: "upload-image",
                span: true,
            },
            {
                name: "displayOrder",
                label: "ترتيب العرض",
                type: "number",
            },
            {
                name: "isFeatured",
                label: "فيديو مميز",
                type: "checkbox",
            },
            {
                name: "isActive",
                label: "الفيديو نشط",
                type: "checkbox",
            },
        ],
    },

    reviews: {
        title: "آراء العملاء",
        singular: "رأي",
        description: "إدارة التقييمات المنشورة على الموقع.",
        defaults: {
            customerName: "",
            rating: 5,
            comment: "",
            isActive: true,
            displayOrder: 0,
        },
        fields: [
            {
                name: "customerName",
                label: "اسم العميل",
                type: "text",
                required: true,
                maxLength: 150,
            },
            {
                name: "rating",
                label: "التقييم",
                type: "rating",
                required: true,
            },
            {
                name: "comment",
                label: "التعليق",
                type: "textarea",
                span: true,
                required: true,
                maxLength: 1000,
            },
            {
                name: "displayOrder",
                label: "ترتيب العرض",
                type: "number",
            },
            {
                name: "isActive",
                label: "الرأي منشور",
                type: "checkbox",
            },
        ],
    },

    sections: {
        title: "أقسام المحتوى",
        singular: "قسم",
        description: "محتوى مرن للصفحات والواجهات العامة.",
        defaults: {
            key: "",
            page: "home",
            title: "",
            subtitle: "",
            body: "",
            imageUrl: "",
            videoUrl: "",
            ctaText: "",
            ctaUrl: "",
            payloadJson: "",
            isActive: true,
            displayOrder: 0,
        },
        fields: [
            {
                name: "key",
                label: "المفتاح",
                type: "text",
                required: true,
                maxLength: 120,
            },
            {
                name: "page",
                label: "الصفحة",
                type: "text",
                required: true,
                maxLength: 80,
            },
            {
                name: "title",
                label: "العنوان",
                type: "text",
                span: true,
                required: true,
                maxLength: 250,
            },
            {
                name: "subtitle",
                label: "العنوان الفرعي",
                type: "text",
                span: true,
                maxLength: 500,
            },
            {
                name: "body",
                label: "النص",
                type: "textarea",
                span: true,
                maxLength: 4000,
            },
            {
                name: "imageUrl",
                label: "الصورة",
                type: "upload-image",
                span: true,
            },
            {
                name: "videoUrl",
                label: "الفيديو",
                type: "upload-video",
                span: true,
            },
            {
                name: "ctaText",
                label: "نص الزر",
                type: "text",
                maxLength: 150,
            },
            {
                name: "ctaUrl",
                label: "رابط الزر",
                type: "url",
                maxLength: 500,
            },
            {
                name: "payloadJson",
                label: "بيانات JSON",
                type: "json",
                span: true,
                maxLength: 4000,
            },
            {
                name: "displayOrder",
                label: "ترتيب العرض",
                type: "number",
            },
            {
                name: "isActive",
                label: "القسم نشط",
                type: "checkbox",
            },
        ],
    },
};
